opkg: Fix usage with pkgrepo.managed
Currently, when using `pkgrepo.managed`, the following error is reported:

```
TypeError: get_repo() got an unexpected keyword argument 'ppa_auth'
```

Fix this by adding `**kwargs` to `get_repo` so that it will absorb unused
kwargs instead of erroring out when given an unknown kwarg. Did the same
thing for all other public APIs in this file.

Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>

Conflicts:
	salt/modules/opkg.py